import streamlit as st
import sqlite3
import pandas as pd

# PAGE CONFIG
st.set_page_config(page_title="Type43 Analytics", page_icon="🏗️", layout="centered")

# DB CONNECTION
def load_data():
    conn = sqlite3.connect("type43.db")
    
    # Load Receipts
    df_receipts = pd.read_sql("SELECT * FROM receipts", conn)
    
    # Load Inventory
    df_inventory = pd.read_sql("SELECT * FROM inventory", conn)
    
    # Load Market Data for Valuation
    df_market = pd.read_sql("SELECT * FROM market_valuations", conn)
    
    conn.close()
    return df_receipts, df_inventory, df_market

# APP LAYOUT
def main():
    # HEADER
    st.title("🏗️ Type43 Analytics")
    st.caption("PROJECT UMBRELLA // AUDIT DASHBOARD")
    st.markdown("---")

    # LOAD DATA
    try:
        df_r, df_i, df_m = load_data()
    except:
        st.error("Database not found. Run 'python init_db.py' first.")
        return

    # METRICS ROW
    col1, col2, col3 = st.columns(3)
    
    with col1:
        total_spent = df_r['total_amount'].sum()
        st.metric("Total Spent (Receipts)", f"${total_spent:,.2f}")
        
    with col2:
        # Calculate Asset Value (Price * Qty)
        # Handle cases where price might be missing
        df_i['value'] = df_i['purchase_price'] * df_i['quantity_on_hand']
        total_assets = df_i['value'].sum()
        st.metric("Physical Assets", f"${total_assets:,.2f}")
        
    with col3:
        # The "Intelligence" Value (Simple placeholder logic for now)
        market_upside = df_m['current_market_price'].sum() - df_i.loc[df_i['id'].isin(df_m['inventory_id']), 'purchase_price'].sum()
        if market_upside > 0:
            st.metric("Inflation Gains", f"+${market_upside:,.2f}", delta_color="normal")
        else:
             st.metric("Inflation Gains", "$0.00")

    st.markdown("---")

    # TABS FOR DATA
    tab1, tab2 = st.tabs(["📄 Verified Receipts", "🛠️ Physical Inventory"])
    
    with tab1:
        st.subheader("IRS Audit Log")
        st.dataframe(df_r[['purchase_date', 'vendor_name', 'total_amount', 'notes']], use_container_width=True)
        
    with tab2:
        st.subheader("Bank Asset Log")
        st.dataframe(df_i[['name', 'category', 'quantity_on_hand', 'purchase_price', 'condition']], use_container_width=True)

    # FOOTER
    st.markdown("---")
    st.markdown("*Generated by Type43 System v1.0*")

if __name__ == "__main__":
    main()